"""
Stress Granule Segmentation Pipeline (LoG-based, multi-scale)

This script performs automated segmentation of stress granules (SGs) from 
fluorescence microscopy TIFF images using a combination of global masking, 
adaptive thresholding, and multi-scale Laplacian-of-Gaussian (LoG) detection.

Pipeline overview:
1. Image normalization:
   Raw TIFF images are converted to float32 and normalized to [0, 1] to ensure 
   consistent intensity scaling across datasets.

2. Cell (cytoplasm) masking:
   A coarse cell mask is generated by applying a heavy Gaussian blur to the image 
   followed by thresholding. This isolates the cytoplasmic region and excludes 
   background.

3. Local adaptive thresholding:
   A local threshold (block-based) is applied within the cytoplasm to identify 
   candidate regions with elevated signal relative to their local neighborhood.

4. LoG particle detection:
   Laplacian-of-Gaussian filtering.

5. Particle filtering:
   Connected components are labeled and filtered based on:
     - Local contrast relative to surrounding cytoplasm
     - Intensity cutoff
   This removes weak or non-specific detections.

6. Feature extraction:
   For each detected granule:
     - Mean intensity
     - Area (size)
   are recorded for downstream analysis.

7. Output:
   A 2-channel segmentation mask is generated:
     - Channel 0: detected granules
     - Channel 1: cytoplasm mask


-------------------------
KEY PARAMETERS TO TUNE
-------------------------

These parameters strongly affect segmentation quality and should be adjusted 
depending on image resolution, noise level, and granule size:

--- Cell mask / background separation ---
- sigma (Gaussian blur for cell mask):
    ndimage.gaussian_filter(..., sigma=20)
    ↑ Larger values = smoother mask, may merge nearby cells
    ↓ Smaller values = more detailed mask, may include noise

- cell_mask threshold:
    cell_mask = blurred > 0.1
    ↑ Higher threshold = stricter cell region (may exclude dim cytoplasm)
    ↓ Lower threshold = more inclusive (may include background)

- Otsu scaling:
    thresh = threshold_otsu(data_norm) * 0.6
    ↑ Increase factor → stricter intensity cutoff
    ↓ Decrease factor → more permissive


--- Local thresholding (structure detection) ---
- block_size (threshold_local):
    block_size=401
    ↑ Larger = smoother, more global behavior
    ↓ Smaller = more sensitive to local variations (can increase noise)

- offset:
    offset=0
    ↑ Increase → fewer pixels classified as signal
    ↓ Decrease → more permissive mask


--- LoG particle detection ---
- sigma values:
    gaussian(..., sigma=8)  # large granules
    gaussian(..., sigma=4)  # small granules
    ↑ Increase sigma → detects larger structures
    ↓ Decrease sigma → detects smaller structures

- percentile thresholds:
    np.percentile(log_big[mask], 95)
    ↑ Higher percentile = stricter detection (fewer false positives)
    ↓ Lower percentile = more sensitive (more detections, more noise)


--- Particle filtering ---
- contrast threshold:
    mean_particle - mean_ring < 0.2 * mean_ring
    ↑ Increase (e.g., 0.3–0.5) → keeps only high-contrast granules
    ↓ Decrease → includes weaker granules

- intensity cutoff:
    cytoplasm[this].max() < 3000
    ↑ Increase → removes dim particles
    ↓ Decrease → keeps dimmer ones


--- Morphological expansion ---
- expansion factor:
    expand_radius = int(np.ceil(r_eq))
    Controls how far the surrounding "ring" is sampled.
    ↑ Larger → broader background estimation
    ↓ Smaller → tighter local comparison


-------------------------
NOTES
-------------------------
- Optimal parameters depend heavily on imaging conditions (SNR, magnification, 
  labeling efficiency).
- Multi-scale LoG is critical for detecting heterogeneous granule sizes.
- Always validate segmentation visually before batch processing.
- Consider parameter sweeps when adapting to new datasets.

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tifffile import imread 
import os
from scipy import ndimage
from skimage.filters import threshold_otsu
from skimage.filters import threshold_local
from skimage.morphology import disk, binary_dilation
from skimage.filters import gaussian, laplace
import tifffile
from scipy.ndimage import binary_fill_holes

#list of experiments, each experiment corresponds to list of the repeat of the experiment 
ExperDirectory = r"D:\manuscripts\SG_GEM paper\SPT"
# experiments = [f for f in os.listdir(ExperDirectory) if 'tifsg' in f.lower()]

# experiments = ['tifSG_01222025_0_15DMSO_500uMNaAr',
#  'tifSG_01222026_0_15perDMSO_6uMRK',
#  'tifSG_01232026_0_15perDMSO_6uMRK_02',
#  'tifSG_01232026_0_15perDMSO_6uMRK_500uMNaAr',
#  'tifSG_01292026_0_15perDMSO',
#  'tifSG_10012025_0_15DMSO_500uMNaAr',
#  'tifSG_10012025_0_15perDMSO',
#  'tifSG_10012025_0_15perDMSO_6uMRK',
#  'tifSG_10012025_0_15perDMSO_6uMRK_500uMNaAr']

experiments = [
 'tifSG_04232026_optimization_afterSG',
 'tifSG_04232026_optimization_beforeSG',
 'tifSG_04302026_0_15perDMSO_100uMNaAr',
 'tifSG_04302026_0_15perDMSO_6uMRK_500uMNaAr',
 'tifSG_09262025_optimization_afterSG',
 'tifSG_09262025_optimization_beforeSG']


save = False

params = {
    'segmentation_id': "LoGsegm_V4",
    "block_size": 401,
    "offset_factor": 0.2,
    "log_sigma": 4,
    "percentile_cutoff": 95,
    "ring_percentile": 60,
    "contrast_threshold": 0.1
}


if False:
    df = pd.DataFrame([params])

    save_dir = os.path.join(ExperDirectory, "SG_segmentation_params")
    os.makedirs(save_dir, exist_ok=True)

    save_csv_path = os.path.join(
        save_dir,
        f"SG_segmentation_params_{params['segmentation_id']}.csv"
    )

    df.to_csv(save_csv_path, index=False)

for experiment in experiments: 
    print(f'{experiment}')
    
    directory = f'{ExperDirectory}/{experiment}/'
    tiff_files = [f for f in os.listdir(directory) if f.endswith('.tif') and not "Probabilities" in f and not "LoGsegm" in f]

    SGs_intensities = []
    SGs_sizes = []
    histogram = []
    
    for tiff_file in tiff_files:
        
        print(tiff_file)
        
        
        file_name = os.path.splitext(tiff_file)[0] 
        save_file = f"{directory}/{file_name}_{params['segmentation_id']}.tif"
        print(save_file)
        data = imread(f"{directory}/{tiff_file}")
        data = data.astype('float32')  # ensure float
        data_norm = (data - np.min(data)) / (np.max(data) - np.min(data))
        
        pixel_values = data.ravel()      
        histogram.extend(pixel_values)        #image histogram
        
        plt.figure()
        
        im = plt.imshow(data, cmap='magma')   # or 'Spectral'
        plt.colorbar(im)                           # <-- this adds the bar
        plt.title(tiff_file)
        plt.axis("off")
        plt.tight_layout()
        plt.show()
        
        
        #---------------
        
        #defining the background area based on first channel 
        blurred = ndimage.gaussian_filter(data_norm, sigma=20)
        thresh = threshold_otsu(data_norm) * 0.6
        cell_mask = blurred > 0.1
        
        # plt.imshow(data_norm, cmap='gray')
        # plt.show()
        plt.imshow(data_norm, cmap='gray')
        plt.imshow(cell_mask, cmap='Reds', alpha=0.4)
        plt.show()
        
        #defining cytoplasm
        cytoplasm = data * cell_mask
                
        # 1️⃣ Local threshold first → get structure mask
        local_thresh = threshold_local(cytoplasm, block_size=params["block_size"], offset=params["offset_factor"]*np.std(cytoplasm))
        
        mask = (cytoplasm > local_thresh) 
        
        # cyto_mask = cell_mask & (cytoplasm > local_thresh)
        # cytoplasm = data * cyto_mask
                        
        # 2️⃣ Small particles
        log_small = laplace(gaussian(cytoplasm, sigma=params["log_sigma"]))
        particles_small = (log_small > np.percentile(log_small[mask], params["percentile_cutoff"])) & mask
             
        # 3️⃣ Filter over particles    
        
        particles = particles_small
        
        particles = binary_fill_holes(particles)
                
        labels, n = ndimage.label(particles)
        
        fig, ax = plt.subplots()
        ax.imshow(cytoplasm, cmap='gray')
        
        kept_mask = np.zeros_like(cytoplasm, dtype=bool)
        
        cytoplasm_background = cytoplasm * (~particles)
        for i in range(1, n + 1):
            this = (labels == i)
        
            # estimate equivalent radius (sqrt of area/pi)
            area = np.sum(this)
            r_eq = np.sqrt(area / np.pi)
        
            # dilate shape ≈ 2× radius
            expand_radius = int(np.ceil(r_eq))  # approx factor ~2× in area
            expanded = binary_dilation(this, disk(expand_radius))
        
            # limit expansion to cytoplasm mask, exclude original particle
            expanded &= (cell_mask > 0)
            ring_mask = expanded & (~this)
        
            median_particle = np.median(cytoplasm[this])

            ring_values = cytoplasm[ring_mask]
            
            if ring_values.size == 0:
                continue

            p60 = np.percentile(ring_values, 60)
            filtered = ring_values[ring_values >= p60]
            median_ring = np.median(filtered)

        
            #skip if contrast too low
            #was 0.2
            if np.isnan(median_ring) or median_particle - median_ring < params["contrast_threshold"] * median_ring:
                continue
                        
            if cytoplasm[this].max() < np.median(cytoplasm_background)*2:
                continue
        
        
            kept_mask |= this
        
            # visualize: particle (green), expanded region (red dashed)
            ax.contour(this, colors='lime', linewidths=0.6)
            ax.contour(expanded, colors='red', linewidths=0.4, linestyles='--')
        
        plt.title("Green = kept particles, Red dashed = expanded contour")
        plt.show()
        

        
#--------SEGMENTATION&SAVE--------------------------------------------
                
        H, W = 512, 512
        seg = np.zeros((H, W, 2), dtype=np.uint8)
        seg[..., 0] = kept_mask.astype(np.uint8)         # channel 0 = particles
        seg[..., 1] = (cell_mask > 0).astype(np.uint8)   # channel 1 = cytoplasm
        
        if save:
            # --- quick plots ---
            fig, axes = plt.subplots(1, 3, figsize=(12, 4))
            axes[0].imshow(seg[..., 0], cmap='gray', vmin=0, vmax=1)
            axes[0].set_title('Particles (channel 0)')
            axes[0].axis('off')
            
            axes[1].imshow(seg[..., 1], cmap='gray', vmin=0, vmax=1)
            axes[1].set_title('Cytoplasm (channel 1)')
            axes[1].axis('off')
            
            # RGB overlay: particles red, cytoplasm green
            rgb = np.zeros((H, W, 3), dtype=np.float32)
            rgb[..., 0] = seg[..., 0]   # red = particles
            rgb[..., 1] = seg[..., 1]   # green = cytoplasm
            axes[2].imshow(cytoplasm, cmap='gray', alpha=0.6)
            axes[2].imshow(rgb, alpha=0.6)
            axes[2].set_title('Overlay (red = particles, green = cytoplasm)')
            axes[2].axis('off')
            
            plt.tight_layout()
            plt.show()
        
        # transpose to (C, Y, X)
        seg_cyx = np.transpose(seg, (2, 0, 1))    # now shape (2, H, W)

        if save: 
            # saves as a 2-channel uint8 TIFF (shape: H x W x 2)
            tifffile.imwrite(save_file, seg_cyx, metadata={'axes': 'YXC'})
            
